### PR TITLE
support new version of android SDK

### PR DESCRIPTION
**Pull request by 1pkg**

### CODE REVIEW

**Comment by subsoap** [comment]
Is the ```xmlns:ads="http://schemas.android.com/apk/lib/com.google.ads"``` line necessary for vibration?

**Comment by 1pkg** [comment]
@subsoap remove `xmlns:ads` from manifest

**Review by adamwestman — APPROVED** [review]
Looks good to merge, nice to get the manifest refactor in there as well to simplify integration.

Speaking of refactors this extension does not follow all best practices when compared with things like the facebook extension, in terms of API script and a proper java folder structure.. but considering how simple this extension is I think less is more :)

**Comment by 1pkg** [comment]
@adamwestman your words make perfect sense to me, this extension is supposed to have minimal functionality to provide a single thing `vibration` and this implementation is okay. What was not okay broken android part, so I just fixed issue with higher version of android SDK support (without this patch extension just crash on higher version of SDKs) and did small refactoring on the way.

P.S. 
I can't hit merge PR button, as I don't have permission.
@adamwestman would you be so kind to also merge it as you've already approved this PR? and maybe also tag it as latest stable version? thx

**Comment by subsoap** [comment]
One more thing, the readme.md was deleted for a version that is now more incomplete probably by mistake. Should keep the old version.

**Comment by 1pkg** [comment]
> One more thing, the readme.md was deleted for a version that is now more incomplete probably by mistake. Should keep the old version.

Why to have two version of same readme.md file? not it just useless duplication, it also causes problems on system that doesn't have case-sensitive file names e.g. MAC.

image

**Comment by subsoap** [comment]
@1pkg You're right, my mistake, I was only reading the changed files. :)

**Pull request merged**
